version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local

services:

  PostgreSQL:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data



  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9009:9009'
    volumes:
      - minio-data:/minio


  API:
    image: evgendas/automatic-verification:1.0.1
    ports:
      - '8092:8092'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgresPlusDialect
    depends_on:
      - PostgreSQL
      - minio
