apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automatic-verification
  namespace: verification
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/auth-url: "https://auth.mysite.domain/api/auth/token/validate"
    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/proxy-pass-headers: "Authorization"
spec:
  rules:
    - http:
        paths:
          - path: /automatic_verification
            pathType: Prefix
            backend:
              service:
                name: automatic-verification
                port:
                  number: 80