apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: verification
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: minio